//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User_Attendance
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> User_Id { get; set; }
        public Nullable<System.Guid> Employee_Id { get; set; }
        public Nullable<double> Latitude_Time_In { get; set; }
        public Nullable<double> Longitude_Time_In { get; set; }
        public Nullable<System.DateTime> Day_Time_In { get; set; }
        public Nullable<System.DateTime> Day_Time_Out { get; set; }
        public string Image_File { get; set; }
        public Nullable<System.Guid> Base_Location_Id { get; set; }
        public Nullable<double> Latitude_Time_Out { get; set; }
        public Nullable<double> Longitude_Time_Out { get; set; }
        public string Description_Time_In { get; set; }
        public string Description_Time_Out { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> Base_Location_Id_Time_Out { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
    }
}
