//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Oganization_Bank_Account
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Code { get; set; }
        public System.Guid Bank_Id { get; set; }
        public string Description { get; set; }
        public string Account_No { get; set; }
        public string Currency_Code { get; set; }
        public string Default_Bank_Account { get; set; }
        public Nullable<decimal> Payment_Order_No { get; set; }
        public string Reference { get; set; }
        public string Customer_Id { get; set; }
        public string ID_copy_1 { get; set; }
        public string Ordering_Customer_Name { get; set; }
        public string Ordering_Customer_Address { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<System.Guid> Workflow_Status_ID { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
    
        public virtual tbl_Organization tbl_Organization { get; set; }
        public virtual tbl_List_Of_Bank tbl_List_Of_Bank { get; set; }
    }
}
