//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Exchange_Files
    {
        public System.Guid id { get; set; }
        public string File_Name { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public Nullable<System.DateTime> Created_By { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public string File_Location { get; set; }
        public string File_Format { get; set; }
        public Nullable<int> File_Size { get; set; }
    }
}
