//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Upload_Staging_Detail
    {
        public System.Guid ID { get; set; }
        public System.Guid Upload_Header_ID { get; set; }
        public string Target_Table { get; set; }
        public string Col_ID { get; set; }
        public string Col_Name { get; set; }
        public string Record_ID { get; set; }
        public string Value { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> Upload_Key { get; set; }
        public Nullable<bool> isDuplicate { get; set; }
        public string Table_Mapping { get; set; }
        public Nullable<bool> isValid { get; set; }
        public Nullable<bool> Is_Mandatory { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
    
        public virtual tbl_Upload_Staging_Header tbl_Upload_Staging_Header { get; set; }
    }
}
