//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BPJS_Healthcare
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Npp_Number { get; set; }
        public string Office_Address { get; set; }
        public string Office_Phone_Number { get; set; }
        public string Office_Fax_Number { get; set; }
        public string e_DABU_login_ID { get; set; }
        public string e_DABU_login_ID_Password { get; set; }
        public Nullable<bool> Def { get; set; }
        public string e_ID_Login_ID { get; set; }
        public string e_ID_Password { get; set; }
        public string Ro { get; set; }
        public string Phone_Mobile_Number { get; set; }
        public string Email { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.Guid> Workflow_Status_ID { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
    
        public virtual tbl_Organization tbl_Organization { get; set; }
    }
}
