//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Function
    {
        public tbl_Function()
        {
            this.tbl_Menu_Function = new HashSet<tbl_Menu_Function>();
        }
    
        public System.Guid id { get; set; }
        public string Function_Code { get; set; }
        public string Function_Description { get; set; }
        public string Icon { get; set; }
        public Nullable<int> Field_Seq { get; set; }
        public Nullable<int> Status_Code { get; set; }
    
        public virtual ICollection<tbl_Menu_Function> tbl_Menu_Function { get; set; }
    }
}
