//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bank_Information
    {
        public tbl_Bank_Information()
        {
            this.tbl_Employee_Payment = new HashSet<tbl_Employee_Payment>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Bank { get; set; }
        public string Account_Number { get; set; }
        public string Account_Name { get; set; }
        public string Debet_Account_ID { get; set; }
        public string Reference { get; set; }
        public string Payment_Set_Code { get; set; }
        public Nullable<bool> Def { get; set; }
        public string Currency_Code { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
    
        public virtual tbl_Organization tbl_Organization { get; set; }
        public virtual ICollection<tbl_Employee_Payment> tbl_Employee_Payment { get; set; }
    }
}
