//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Attendance_History_Upload
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public long Upload_Number { get; set; }
        public Nullable<System.Guid> Attendance_Summary_ID { get; set; }
        public string Uploaded_By { get; set; }
        public Nullable<System.DateTime> Uploaded_Datetime { get; set; }
        public string Path_File { get; set; }
        public Nullable<int> Sync_Status { get; set; }
        public Nullable<int> Sync_Row { get; set; }
        public Nullable<int> Sync_Success { get; set; }
        public Nullable<int> Sync_Error { get; set; }
        public Nullable<int> Sync_Warning { get; set; }
        public string Device_Finger { get; set; }
    }
}
