//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payslip_Setting
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public System.Guid Payslip_ID { get; set; }
        public Nullable<int> Is_Active { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
    
        public virtual tbl_Payslip_Template tbl_Payslip_Template { get; set; }
    }
}
