//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Reminder_User
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Reminder_ID { get; set; }
        public Nullable<System.Guid> User_ID { get; set; }
    
        public virtual tbl_Reminder tbl_Reminder { get; set; }
    }
}
