//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payroll_Slip
    {
        public tbl_Payroll_Slip()
        {
            this.tbl_Payroll_Slip_Component = new HashSet<tbl_Payroll_Slip_Component>();
            this.tbl_Payroll_Slip_Employee = new HashSet<tbl_Payroll_Slip_Employee>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid Payroll_Period_ID { get; set; }
        public int Run_From { get; set; }
        public int Run_To { get; set; }
        public string Payslip_Distribution { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
        public bool Exclude_Zero_Value { get; set; }
        public string Email_Subject { get; set; }
        public string Email_Note { get; set; }
        public Nullable<System.DateTime> Generate_Date { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Text_Info { get; set; }
        public bool Final_Version { get; set; }
        public string Payroll_Slip_Type { get; set; }
    
        public virtual tbl_Payroll_Period_Detail tbl_Payroll_Period_Detail { get; set; }
        public virtual ICollection<tbl_Payroll_Slip_Component> tbl_Payroll_Slip_Component { get; set; }
        public virtual ICollection<tbl_Payroll_Slip_Employee> tbl_Payroll_Slip_Employee { get; set; }
    }
}
