//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payroll_Period_Detail
    {
        public tbl_Payroll_Period_Detail()
        {
            this.tbl_Payroll_Calculation = new HashSet<tbl_Payroll_Calculation>();
            this.tbl_Additional_Payroll = new HashSet<tbl_Additional_Payroll>();
            this.tbl_Payroll_Variable = new HashSet<tbl_Payroll_Variable>();
            this.tbl_Payroll_Slip = new HashSet<tbl_Payroll_Slip>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public System.DateTime Tax_Period { get; set; }
        public System.DateTime Period_Start_Date { get; set; }
        public System.DateTime Period_End_Date { get; set; }
    
        public virtual ICollection<tbl_Payroll_Calculation> tbl_Payroll_Calculation { get; set; }
        public virtual tbl_Payroll_Period tbl_Payroll_Period { get; set; }
        public virtual ICollection<tbl_Additional_Payroll> tbl_Additional_Payroll { get; set; }
        public virtual ICollection<tbl_Payroll_Variable> tbl_Payroll_Variable { get; set; }
        public virtual ICollection<tbl_Payroll_Slip> tbl_Payroll_Slip { get; set; }
    }
}
