//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Current_Version
    {
        public System.Guid id { get; set; }
        public string Record_ID { get; set; }
        public string Url_Menu { get; set; }
        public string Column_Name { get; set; }
        public string Value { get; set; }
        public Nullable<int> Curr_Version { get; set; }
        public Nullable<int> Latest_Version { get; set; }
    }
}
