//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee_Document
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string Path { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public string File_Name { get; set; }
        public string FIle_Location { get; set; }
        public string File_Format { get; set; }
        public Nullable<int> File_Size { get; set; }
        public string Created_DateTime_Varchar { get; set; }
    
        public virtual tbl_Employee tbl_Employee { get; set; }
        public virtual tbl_Organization tbl_Organization { get; set; }
    }
}
