//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Organization_Branch_NPWP
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Organization_Branch_Code { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Logo { get; set; }
        public string Bukti_218 { get; set; }
        public Nullable<decimal> Bukti_218_Last_No { get; set; }
        public Nullable<decimal> Bukti_218_X { get; set; }
        public string NPWP_No { get; set; }
        public string KPP_Name { get; set; }
        public string KPP_Address { get; set; }
        public string KPP_Location { get; set; }
        public string Nama_Penyetor { get; set; }
        public string SPT_Location { get; set; }
        public Nullable<System.DateTime> SPT_Date { get; set; }
        public string Signer_Name { get; set; }
        public string Signer_Position { get; set; }
        public string Signer_NPWP { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<System.Guid> Workflow_Status_ID { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
    
        public virtual tbl_Organization tbl_Organization { get; set; }
    }
}
