//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Third_Party_Employee
    {
        public System.Guid id { get; set; }
        public System.Guid Employee_ID { get; set; }
        public System.Guid Third_Party_Content_ID { get; set; }
        public string Full_Name { get; set; }
        public string Gender { get; set; }
        public string Identity_Type { get; set; }
        public string Identity_Number { get; set; }
        public string Phone { get; set; }
        public string Email_Address { get; set; }
        public string Job { get; set; }
        public string Payment_Type { get; set; }
        public string Location { get; set; }
    }
}
