//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Upload_Staging_Header
    {
        public tbl_Upload_Staging_Header()
        {
            this.tbl_Upload_Staging_Detail = new HashSet<tbl_Upload_Staging_Detail>();
        }
    
        public System.Guid ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public string Category_Type { get; set; }
        public Nullable<System.Guid> Upload_Number_ID { get; set; }
    
        public virtual tbl_Upload_Staging tbl_Upload_Staging { get; set; }
        public virtual ICollection<tbl_Upload_Staging_Detail> tbl_Upload_Staging_Detail { get; set; }
    }
}
