//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payroll_Tax_Correction
    {
        public System.Guid ID { get; set; }
        public System.Guid Calculation_ID { get; set; }
        public Nullable<System.DateTime> Tax_Period { get; set; }
        public string Tax_ID { get; set; }
        public Nullable<int> Pembetulan { get; set; }
        public Nullable<int> Run { get; set; }
    
        public virtual tbl_Payroll_Calculation tbl_Payroll_Calculation { get; set; }
    }
}
