//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Organization_Group_Detail
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Organization_Group_ID { get; set; }
        public Nullable<System.Guid> Organization_Client_ID { get; set; }
        public string Relationship_Type { get; set; }
    
        public virtual tbl_Organization_Group tbl_Organization_Group { get; set; }
    }
}
