//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Reminder
    {
        public tbl_Reminder()
        {
            this.tbl_Reminder_Employee = new HashSet<tbl_Reminder_Employee>();
            this.tbl_Reminder_User = new HashSet<tbl_Reminder_User>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public string Reminder_Type { get; set; }
        public string Notification_Type { get; set; }
        public bool All_Employee { get; set; }
        public Nullable<System.Guid> Reference_ID { get; set; }
        public bool Reminder_Status { get; set; }
    
        public virtual ICollection<tbl_Reminder_Employee> tbl_Reminder_Employee { get; set; }
        public virtual ICollection<tbl_Reminder_User> tbl_Reminder_User { get; set; }
    }
}
