//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User_Mobile
    {
        public System.Guid User_Id { get; set; }
        public System.Guid Employee_Id { get; set; }
        public Nullable<System.DateTime> Last_Login_Date { get; set; }
        public Nullable<bool> Is_login { get; set; }
    
        public virtual tbl_Employee tbl_Employee { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
