//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Order
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> User_Order_Id { get; set; }
        public string Billing_To { get; set; }
        public string Billing_Address { get; set; }
        public string Package { get; set; }
        public Nullable<int> Number_Employee { get; set; }
        public Nullable<int> Number_Component { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> Month_Period_Start { get; set; }
        public Nullable<System.DateTime> Month_Period_End { get; set; }
        public Nullable<double> Total_Package_Price { get; set; }
        public Nullable<double> Cost_Implementation { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<double> Total_Cashback { get; set; }
        public Nullable<double> Total_Discount { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Total_Payment { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<System.DateTime> Valid_Start_Payment { get; set; }
        public Nullable<System.DateTime> Valid_End_Payment { get; set; }
        public Nullable<int> Payment_Status { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.Guid> Workflow_Status_ID { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public string Order_No { get; set; }
        public string Payment_Type { get; set; }
        public string Payment_Status_Description { get; set; }
    }
}
