//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tax
    {
        public tbl_Tax()
        {
            this.tbl_Tax_Status_Effective_Year = new HashSet<tbl_Tax_Status_Effective_Year>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Tax_No { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
        public Nullable<System.DateTime> Revoke_Date { get; set; }
        public string Salary_Tax_Policy { get; set; }
        public Nullable<double> Previous_Net_Income { get; set; }
        public Nullable<double> Previous_Tax_Paid { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
    
        public virtual ICollection<tbl_Tax_Status_Effective_Year> tbl_Tax_Status_Effective_Year { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
