//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Menu_Function
    {
        public tbl_Menu_Function()
        {
            this.tbl_Menu_Function_Restriction = new HashSet<tbl_Menu_Function_Restriction>();
            this.tbl_Organization_Menu = new HashSet<tbl_Organization_Menu>();
            this.tbl_Notification_Template = new HashSet<tbl_Notification_Template>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid Menu_ID { get; set; }
        public Nullable<System.Guid> Function_ID { get; set; }
        public Nullable<int> Status_Code { get; set; }
    
        public virtual tbl_Function tbl_Function { get; set; }
        public virtual ICollection<tbl_Menu_Function_Restriction> tbl_Menu_Function_Restriction { get; set; }
        public virtual ICollection<tbl_Organization_Menu> tbl_Organization_Menu { get; set; }
        public virtual tbl_Menu tbl_Menu { get; set; }
        public virtual ICollection<tbl_Notification_Template> tbl_Notification_Template { get; set; }
    }
}
