//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Attendance_Request
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public System.Guid User_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public System.DateTime Day_Time_In { get; set; }
        public System.DateTime Day_Time_Out { get; set; }
        public Nullable<System.DateTime> Created_Datetime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Approved_By { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public string Authorized_Remark { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public System.DateTime Date { get; set; }
    }
}
