//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public tbl_User()
        {
            this.tbl_Organization_User = new HashSet<tbl_Organization_User>();
            this.tbl_User_Role = new HashSet<tbl_User_Role>();
            this.tbl_User_Organization_Team = new HashSet<tbl_User_Organization_Team>();
        }
    
        public System.Guid id { get; set; }
        public string LDAP { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int Login_Attempt { get; set; }
        public Nullable<bool> Is_Locked { get; set; }
        public Nullable<bool> Is_Mobile_Phone { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.Guid> Workflow_Status_ID { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public Nullable<int> Invalid_Password { get; set; }
    
        public virtual ICollection<tbl_Organization_User> tbl_Organization_User { get; set; }
        public virtual ICollection<tbl_User_Role> tbl_User_Role { get; set; }
        public virtual ICollection<tbl_User_Organization_Team> tbl_User_Organization_Team { get; set; }
        public virtual tbl_User_Mobile tbl_User_Mobile { get; set; }
    }
}
