//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Message
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Beneficiary { get; set; }
        public string Message_Title { get; set; }
        public string Message { get; set; }
        public bool Is_Read { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
    }
}
