//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Holiday_Calendar_Organization
    {
        public tbl_Holiday_Calendar_Organization()
        {
            this.tbl_Holiday_Calendar_Organization_Details = new HashSet<tbl_Holiday_Calendar_Organization_Details>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public Nullable<System.Guid> Holiday_Calendar_ID { get; set; }
        public Nullable<bool> Is_default { get; set; }
        public System.DateTime Holiday_Date { get; set; }
        public string Holiday_Name { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public string Location { get; set; }
    
        public virtual tbl_Holiday_Calendar tbl_Holiday_Calendar { get; set; }
        public virtual ICollection<tbl_Holiday_Calendar_Organization_Details> tbl_Holiday_Calendar_Organization_Details { get; set; }
        public virtual tbl_Organization tbl_Organization { get; set; }
    }
}
