//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Compensation_Benefit
    {
        public System.Guid id { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Type_Compensation_Benefit { get; set; }
        public System.Guid Component_Linkage { get; set; }
        public string Currency { get; set; }
        public decimal Budget { get; set; }
        public string Period { get; set; }
        public string Upload_Number { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.Guid> Workflow_Status_ID { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
    
        public virtual tbl_Employee_Payroll_Component tbl_Employee_Payroll_Component { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
