//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payslip_Template
    {
        public tbl_Payslip_Template()
        {
            this.tbl_Payslip_Setting = new HashSet<tbl_Payslip_Setting>();
            this.tbl_Payslip_Template_Detail = new HashSet<tbl_Payslip_Template_Detail>();
        }
    
        public System.Guid ID { get; set; }
        public string Report_Name { get; set; }
        public string Target { get; set; }
        public Nullable<int> Is_Default { get; set; }
        public string Paper_Size { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<tbl_Payslip_Setting> tbl_Payslip_Setting { get; set; }
        public virtual ICollection<tbl_Payslip_Template_Detail> tbl_Payslip_Template_Detail { get; set; }
    }
}
