//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Organization_Team
    {
        public tbl_Organization_Team()
        {
            this.tbl_Client_Organization_Team = new HashSet<tbl_Client_Organization_Team>();
            this.tbl_User_Organization_Team = new HashSet<tbl_User_Organization_Team>();
            this.tbl_Organization_Group = new HashSet<tbl_Organization_Group>();
        }
    
        public System.Guid id { get; set; }
        public string Team_Code { get; set; }
        public string Team_Description { get; set; }
        public System.Guid Organization_ID { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public System.Guid Workflow_Status_ID { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
    
        public virtual tbl_Organization tbl_Organization { get; set; }
        public virtual ICollection<tbl_Client_Organization_Team> tbl_Client_Organization_Team { get; set; }
        public virtual ICollection<tbl_User_Organization_Team> tbl_User_Organization_Team { get; set; }
        public virtual ICollection<tbl_Organization_Group> tbl_Organization_Group { get; set; }
    }
}
