//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer_Notice
    {
        public System.Guid id { get; set; }
        public string Company_Name { get; set; }
        public Nullable<int> Number_Employee { get; set; }
        public string Company_Website { get; set; }
        public string Contact_Name { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Meeting_Schedule { get; set; }
        public string Meeting_Location { get; set; }
        public string Many_Customers { get; set; }
        public string Curently_Partner { get; set; }
        public string Primary_Competitors { get; set; }
        public string Type_Form { get; set; }
        public string Remark { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Pricing { get; set; }
        public string Partnership_Interest { get; set; }
    }
}
