//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Additional_Payroll
    {
        public tbl_Additional_Payroll()
        {
            this.tbl_Additional_Payroll_Detail = new HashSet<tbl_Additional_Payroll_Detail>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public string Employee_Status { get; set; }
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<tbl_Additional_Payroll_Detail> tbl_Additional_Payroll_Detail { get; set; }
        public virtual tbl_Payroll_Period_Detail tbl_Payroll_Period_Detail { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
