//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Education
    {
        public System.Guid id { get; set; }
        public string Education_Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status_Code { get; set; }
    }
}
