//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Generate_Bank_File_Details
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Generate_Bank_File_ID { get; set; }
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public string Employee_No { get; set; }
        public string Employee_Bank_Code { get; set; }
        public string Employee_Bank_Account { get; set; }
        public Nullable<decimal> Employee_Salary_Transferred { get; set; }
        public string Currency_Code { get; set; }
        public string Account_Name { get; set; }
        public string Branch_Code { get; set; }
        public string Personal_Email_Address { get; set; }
    }
}
