//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Upload_Mapping
    {
        public System.Guid ID { get; set; }
        public string Category_Type { get; set; }
        public string Target_Table { get; set; }
        public string Col_ID { get; set; }
        public string Col_Name { get; set; }
        public string Table_Mapping { get; set; }
        public Nullable<int> Seq { get; set; }
        public string Foreign_Key_Table { get; set; }
        public string Masking_Field { get; set; }
        public Nullable<bool> Checker { get; set; }
        public Nullable<bool> Is_Authorize { get; set; }
        public Nullable<bool> Checker_Update { get; set; }
    }
}
