//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HeadOffice_Branch
    {
        public tbl_HeadOffice_Branch()
        {
            this.tbl_HeadOffice_Branch_Location = new HashSet<tbl_HeadOffice_Branch_Location>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public Nullable<System.Guid> Parent_Head_Office_ID { get; set; }
        public string Type { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Tax_Address { get; set; }
        public string Tax_District { get; set; }
        public string Tax_Village { get; set; }
        public string Tax_Regency_City { get; set; }
        public string Tax_Province { get; set; }
        public string Tax_Country { get; set; }
        public string Tax_Post_Code { get; set; }
        public string Mail_Address { get; set; }
        public string Mail_District { get; set; }
        public string Mail_Village { get; set; }
        public string Mail_Regency_City { get; set; }
        public string Mail_Province { get; set; }
        public string Mail_Country { get; set; }
        public string Mail_Post_Code { get; set; }
        public string Location { get; set; }
        public string HO_Branch_Phone_Number { get; set; }
        public string HO_Branch_Fax_Number { get; set; }
        public string HO_Branch_TAX_ID { get; set; }
        public string Signer_Name { get; set; }
        public string Signer_Position_Code { get; set; }
        public string Signer_Position_Description { get; set; }
        public string Signers_Tax_ID { get; set; }
        public string Signatory_Type { get; set; }
        public string Tax_e_Billing_Login_ID { get; set; }
        public string Tax_e_Billing_Login_Password { get; set; }
        public string Tax_Office_Name { get; set; }
        public string Tax_Office_Address { get; set; }
        public string Tax_Office_AR { get; set; }
        public string AR_Phone_Number { get; set; }
        public string AR_Email { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.Guid> Workflow_Status_ID { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
    
        public virtual ICollection<tbl_HeadOffice_Branch_Location> tbl_HeadOffice_Branch_Location { get; set; }
        public virtual tbl_Organization tbl_Organization { get; set; }
    }
}
