//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Log_WebService
    {
        public System.Guid id { get; set; }
        public string User_Id { get; set; }
        public string Menu { get; set; }
        public Nullable<System.DateTime> Access_DateTime { get; set; }
        public string Method { get; set; }
        public string Employee_Id { get; set; }
        public string Device { get; set; }
    }
}
