//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Organization_Contact
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Office_Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Record_Statuus { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.DateTime> Created_Date_Time { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Update_Date_Time { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public string Remarks { get; set; }
        public string Personal_Phone { get; set; }
        public Nullable<int> Status_Code { get; set; }
    }
}
