//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Additional_Payroll_Detail
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Additional_Payroll_ID { get; set; }
        public string Additional_Component { get; set; }
        public string Additional_Currency { get; set; }
        public Nullable<decimal> Additional_Amount { get; set; }
        public string Additional_Remark { get; set; }
        public string Additional_Upload_No { get; set; }
        public Nullable<System.DateTime> Additional_Transaction_Date { get; set; }
    
        public virtual tbl_Additional_Payroll tbl_Additional_Payroll { get; set; }
    }
}
