//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Upload_Staging
    {
        public tbl_Upload_Staging()
        {
            this.tbl_Upload_Staging_Header = new HashSet<tbl_Upload_Staging_Header>();
        }
    
        public System.Guid ID { get; set; }
        public string Upload_Number { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public string Authorized_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Total_Record { get; set; }
        public string Url { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Relative_Column { get; set; }
        public Nullable<int> Relative_Row { get; set; }
        public long Upload_Identity { get; set; }
        public Nullable<int> Success { get; set; }
        public Nullable<int> Failed { get; set; }
        public Nullable<int> Warning { get; set; }
        public string Upload_Status { get; set; }
        public string Failed_Message { get; set; }
    
        public virtual ICollection<tbl_Upload_Staging_Header> tbl_Upload_Staging_Header { get; set; }
    }
}
