//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Third_Party_Log
    {
        public System.Guid id { get; set; }
        public System.Guid Employee_ID { get; set; }
        public System.Guid Third_Party_Content_ID { get; set; }
        public System.DateTime Click_Date { get; set; }
        public bool Is_Agree { get; set; }
    }
}
