//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Notification_Template
    {
        public System.Guid id { get; set; }
        public string Template_Code { get; set; }
        public Nullable<System.Guid> Menu_Function_Id { get; set; }
        public string Body { get; set; }
        public string Description { get; set; }
        public string Mapping_Value { get; set; }
        public Nullable<int> Is_Private_Message { get; set; }
        public Nullable<int> Is_Email { get; set; }
    
        public virtual tbl_Menu_Function tbl_Menu_Function { get; set; }
    }
}
