//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Apply_Leave_Detail
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Leave_Id { get; set; }
        public Nullable<System.DateTime> Leave_Date { get; set; }
        public Nullable<System.TimeSpan> Start { get; set; }
        public Nullable<System.TimeSpan> End { get; set; }
    
        public virtual tbl_Apply_Leave tbl_Apply_Leave { get; set; }
    }
}
