//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Apply_Leave
    {
        public tbl_Apply_Leave()
        {
            this.tbl_Apply_Leave_Detail = new HashSet<tbl_Apply_Leave_Detail>();
        }
    
        public System.Guid Id { get; set; }
        public string Leave_Type { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public string Duration_Type { get; set; }
        public Nullable<System.TimeSpan> Duration_Time_Start { get; set; }
        public Nullable<System.TimeSpan> Duration_Time_End { get; set; }
        public string Comment { get; set; }
        public System.Guid Organization_id { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public System.Guid Employee_Id { get; set; }
        public Nullable<System.DateTime> Period_Start { get; set; }
        public Nullable<System.DateTime> Period_End { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Is_Reset { get; set; }
        public string Remark_Reset { get; set; }
        public string Reset_By { get; set; }
        public string PathFile { get; set; }
    
        public virtual ICollection<tbl_Apply_Leave_Detail> tbl_Apply_Leave_Detail { get; set; }
    }
}
