//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Audit_Trail
    {
        public System.Guid id { get; set; }
        public string Record_ID { get; set; }
        public string Url_Menu { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public string Event { get; set; }
        public string Column_Name { get; set; }
        public string Value_Before { get; set; }
        public string Value_After { get; set; }
        public string Value_Comparison { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.Guid> Version_Id { get; set; }
        public string Header_Id { get; set; }
    }
}
