//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_List_Of_Bank
    {
        public tbl_List_Of_Bank()
        {
            this.tbl_Employee_Payment = new HashSet<tbl_Employee_Payment>();
            this.tbl_Branch_List_Of_Bank = new HashSet<tbl_Branch_List_Of_Bank>();
        }
    
        public System.Guid id { get; set; }
        public string Bank_Code { get; set; }
        public string Description { get; set; }
        public string BI_Bank_Code { get; set; }
        public string Swift_Code { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.Guid> Workflow_Status_ID { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public Nullable<bool> Is_Mandatory { get; set; }
        public string Is_Length { get; set; }
        public Nullable<bool> Online_Payment { get; set; }
    
        public virtual ICollection<tbl_Employee_Payment> tbl_Employee_Payment { get; set; }
        public virtual ICollection<tbl_Branch_List_Of_Bank> tbl_Branch_List_Of_Bank { get; set; }
    }
}
