//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Language
    {
        public System.Guid id { get; set; }
        public string Code { get; set; }
        public string Table_Name { get; set; }
        public string Language { get; set; }
        public string Column_Name { get; set; }
        public string Label { get; set; }
        public bool Is_Audit { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<bool> Is_Amount { get; set; }
    }
}
