//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Organization_Working_Time
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Working_Time_Code { get; set; }
        public string Working_Time_Description { get; set; }
        public string Working_Day { get; set; }
        public string Base_Working_Day { get; set; }
        public Nullable<int> Base_Fix { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public Nullable<int> Base_Calendar_Day { get; set; }
        public Nullable<System.TimeSpan> Schedule_Time_In { get; set; }
        public Nullable<System.TimeSpan> Schedule_Time_Out { get; set; }
    
        public virtual tbl_Organization tbl_Organization { get; set; }
    }
}
