//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payroll_Slip_Employee
    {
        public System.Guid id { get; set; }
        public System.Guid Payroll_Slip_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Generation_Number { get; set; }
        public string Payslip_Status { get; set; }
        public string Payslip_Url { get; set; }
    
        public virtual tbl_Payroll_Slip tbl_Payroll_Slip { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
