//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Attendance_Mapping_DeviceOrg
    {
        public System.Guid id { get; set; }
        public System.Guid Attendance_Device_ID { get; set; }
        public System.Guid Organization_ID { get; set; }
        public Nullable<int> Is_Default { get; set; }
    }
}
