//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Report_Column
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Organization_Id { get; set; }
        public string Col_Name { get; set; }
        public string Col_Description { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> Is_Summary { get; set; }
        public Nullable<bool> Is_Grouping { get; set; }
    }
}
