//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Trx_Bank_Transfer_Detail
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Trx_Bank_Transfer_ID { get; set; }
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public string Employee_No { get; set; }
        public string Employee_Bank_Code { get; set; }
        public string Employee_Bank_Account { get; set; }
        public Nullable<decimal> Employee_Salary_Transferred { get; set; }
        public string Currency_Code { get; set; }
        public string Account_Name { get; set; }
        public string Branch_Code { get; set; }
        public string Personal_Email_Address { get; set; }
        public string Reference_Number { get; set; }
        public string Process_Status { get; set; }
        public string Beneficiary_BI_Bank_Code { get; set; }
        public Nullable<int> Beneficiary_Status { get; set; }
        public Nullable<int> Beneficiary_Type { get; set; }
        public string Beneficiary_Address { get; set; }
        public Nullable<int> Run { get; set; }
        public string Full_Name { get; set; }
        public string Transfer_Type_Detail { get; set; }
        public string Description { get; set; }
    
        public virtual tbl_Trx_Bank_Transfer tbl_Trx_Bank_Transfer { get; set; }
    }
}
