//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payslip_Template_Detail
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Payslip_Template_Id { get; set; }
        public string Field_Name { get; set; }
        public string Field_Value { get; set; }
        public int Sequence { get; set; }
        public string Group_Name { get; set; }
        public string Position { get; set; }
    
        public virtual tbl_Payslip_Template tbl_Payslip_Template { get; set; }
    }
}
