//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact_Support
    {
        public System.Guid id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public string Tipe { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Send_Email_Type { get; set; }
        public string Phone_No { get; set; }
    }
}
