//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee_Overtime
    {
        public System.Guid Id { get; set; }
        public System.Guid Employee_ID { get; set; }
        public System.Guid Organization_ID { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public Nullable<System.TimeSpan> Start { get; set; }
        public Nullable<System.TimeSpan> End { get; set; }
        public string Purpose { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_Datetime { get; set; }
        public string Authorized_By { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Is_Reset { get; set; }
        public string Reset_Remark { get; set; }
        public Nullable<System.DateTime> Reset_DateTime { get; set; }
        public string Reset_By { get; set; }
        public Nullable<System.TimeSpan> Actual_Start { get; set; }
        public Nullable<System.TimeSpan> Actual_End { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public Nullable<System.TimeSpan> Duration_Actual { get; set; }
    }
}
