//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Job_Code
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Job_Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status_Code { get; set; }
    
        public virtual tbl_Organization tbl_Organization { get; set; }
    }
}
