//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payroll_Transaction
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Payroll_Calculation_ID { get; set; }
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Payroll_Component_Code { get; set; }
        public string Formula { get; set; }
        public string Component_Payroll { get; set; }
        public string Component_Value { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<bool> isSuccess { get; set; }
        public string Reason { get; set; }
        public string Currency { get; set; }
        public string Calculation_Basic { get; set; }
        public Nullable<bool> Is_Prorate_New_Resign { get; set; }
        public Nullable<bool> Is_Prorate { get; set; }
        public string Prorate_Base { get; set; }
        public Nullable<double> Exchange_Rate { get; set; }
        public string Taxable_Type { get; set; }
        public string Frequency { get; set; }
        public string Tax_Policy { get; set; }
        public Nullable<bool> Tax_Deduction { get; set; }
        public string Payroll_Component_Description { get; set; }
        public Nullable<double> Original_Amount { get; set; }
        public Nullable<double> Rounding_Amount { get; set; }
        public string Amount_Type { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public Nullable<double> Calculate_Amount { get; set; }
        public Nullable<double> Additional_Payroll { get; set; }
        public Nullable<double> Additional_Income { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<int> Pembetulan { get; set; }
        public string Sign { get; set; }
    
        public virtual tbl_Payroll_Calculation tbl_Payroll_Calculation { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
