//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Loan
    {
        public System.Guid id { get; set; }
        public string Loan_No { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Type_Loan { get; set; }
        public System.Guid Component_Linkage { get; set; }
        public string Currency { get; set; }
        public decimal Loan_Amount { get; set; }
        public decimal Outstanding_Loan_Amount { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public decimal Installment_Amount { get; set; }
        public decimal Tenor { get; set; }
        public decimal Outstanding_Tenor { get; set; }
        public string Upload_Number { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.Guid> Workflow_Status_ID { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
    }
}
