//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payroll_Variable
    {
        public tbl_Payroll_Variable()
        {
            this.tbl_Payroll_Variable_Detail = new HashSet<tbl_Payroll_Variable_Detail>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public Nullable<decimal> Working_Day { get; set; }
        public Nullable<decimal> Overtime_Day { get; set; }
        public Nullable<decimal> Absent_Day { get; set; }
        public Nullable<decimal> Weekday_Tier1 { get; set; }
        public Nullable<decimal> Weekday_Tier2 { get; set; }
        public Nullable<decimal> Weekday_Tier3 { get; set; }
        public Nullable<decimal> Holiday_Tier1 { get; set; }
        public Nullable<decimal> Holiday_Tier2 { get; set; }
        public Nullable<decimal> Holiday_Tier3 { get; set; }
        public Nullable<decimal> HIS_Tier1 { get; set; }
        public Nullable<decimal> HIS_Tier2 { get; set; }
        public Nullable<decimal> HIS_Tier3 { get; set; }
        public Nullable<decimal> Total_Overtime { get; set; }
        public string Upload_Number { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public string Batch_No { get; set; }
    
        public virtual tbl_Payroll_Period_Detail tbl_Payroll_Period_Detail { get; set; }
        public virtual ICollection<tbl_Payroll_Variable_Detail> tbl_Payroll_Variable_Detail { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
