//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payroll_Slip_Component
    {
        public System.Guid id { get; set; }
        public System.Guid Payroll_Slip_ID { get; set; }
        public System.Guid Organization_Payroll_Component_ID { get; set; }
    
        public virtual tbl_Organization_Payroll_Component tbl_Organization_Payroll_Component { get; set; }
        public virtual tbl_Organization_Payroll_Component tbl_Organization_Payroll_Component1 { get; set; }
        public virtual tbl_Organization_Payroll_Component tbl_Organization_Payroll_Component2 { get; set; }
        public virtual tbl_Organization_Payroll_Component tbl_Organization_Payroll_Component3 { get; set; }
        public virtual tbl_Organization_Payroll_Component tbl_Organization_Payroll_Component4 { get; set; }
        public virtual tbl_Organization_Payroll_Component tbl_Organization_Payroll_Component5 { get; set; }
        public virtual tbl_Organization_Payroll_Component tbl_Organization_Payroll_Component6 { get; set; }
        public virtual tbl_Organization_Payroll_Component tbl_Organization_Payroll_Component7 { get; set; }
        public virtual tbl_Payroll_Slip tbl_Payroll_Slip { get; set; }
    }
}
