//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HeadOffice_Branch_Location
    {
        public System.Guid id { get; set; }
        public System.Guid HeadOffice_Branch_ID { get; set; }
        public string Location { get; set; }
    
        public virtual tbl_HeadOffice_Branch tbl_HeadOffice_Branch { get; set; }
    }
}
