//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Attendance_Device
    {
        public System.Guid id { get; set; }
        public string Device_Finger { get; set; }
        public string Template { get; set; }
        public string Delimeter { get; set; }
        public string Format_File { get; set; }
        public Nullable<int> Error_Index { get; set; }
    }
}
