//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee_Payment
    {
        public System.Guid id { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Payment_Type_ID { get; set; }
        public Nullable<System.Guid> Payment_Bank_ID { get; set; }
        public string Employee_Bank_Account { get; set; }
        public Nullable<System.Guid> Employee_Bank_ID { get; set; }
        public Nullable<System.Guid> Employee_Bank_Branch_ID { get; set; }
        public string Currency_Code { get; set; }
        public string Account_Name { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.Guid> Workflow_Status_ID { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
    
        public virtual tbl_List_Of_Bank tbl_List_Of_Bank { get; set; }
        public virtual tbl_Branch_List_Of_Bank tbl_Branch_List_Of_Bank { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
        public virtual tbl_Bank_Information tbl_Bank_Information { get; set; }
    }
}
