//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tax_Period
    {
        public tbl_Tax_Period()
        {
            this.tbl_Tax_Period_Month = new HashSet<tbl_Tax_Period_Month>();
            this.tbl_Payroll_Period = new HashSet<tbl_Payroll_Period>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public int def { get; set; }
        public int Tax_Year { get; set; }
        public System.DateTime Tax_Peroid_From { get; set; }
        public System.DateTime Tax_Peroid_To { get; set; }
        public string Tax_Peroid_Status { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public Nullable<System.DateTime> Closing_Date { get; set; }
    
        public virtual tbl_Organization tbl_Organization { get; set; }
        public virtual ICollection<tbl_Tax_Period_Month> tbl_Tax_Period_Month { get; set; }
        public virtual ICollection<tbl_Payroll_Period> tbl_Payroll_Period { get; set; }
    }
}
