//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bank_Account
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Account_Number { get; set; }
        public Nullable<System.Guid> Bank_Code_ID { get; set; }
        public string Currency_Code { get; set; }
        public string Account_Name { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string Amount { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<System.Guid> Workflow_Status_ID { get; set; }
        public Nullable<System.DateTime> Create_Date_Time { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Update_Date_Time { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
    }
}
