//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Report_Payroll_Calculation
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public string Payroll_Period_ID { get; set; }
        public Nullable<int> Run { get; set; }
        public string Head_Office { get; set; }
        public string Location { get; set; }
        public string Employment_Status { get; set; }
        public string Employee_Status { get; set; }
        public string Deputation { get; set; }
        public string Division { get; set; }
        public string Department { get; set; }
        public string Grade { get; set; }
        public string Position { get; set; }
        public string Payroll_Report_Code { get; set; }
        public string Report_Group { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
    }
}
