//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cut_Off_Period
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Payroll_Schedule_ID { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public Nullable<System.DateTime> Cut_Off_Start { get; set; }
        public Nullable<System.DateTime> Cut_Off_End { get; set; }
        public Nullable<int> Cut_Off_Year { get; set; }
    }
}
