//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public tbl_Employee()
        {
            this.tbl_Additional_Payroll = new HashSet<tbl_Additional_Payroll>();
            this.tbl_Compensation_Benefit = new HashSet<tbl_Compensation_Benefit>();
            this.tbl_Payroll_Transaction = new HashSet<tbl_Payroll_Transaction>();
            this.tbl_Payroll_Slip_Employee = new HashSet<tbl_Payroll_Slip_Employee>();
            this.tbl_Employee_Appointment = new HashSet<tbl_Employee_Appointment>();
            this.tbl_Employee_Family = new HashSet<tbl_Employee_Family>();
            this.tbl_Employee_ID_Information = new HashSet<tbl_Employee_ID_Information>();
            this.tbl_Employee_Payment = new HashSet<tbl_Employee_Payment>();
            this.tbl_Payroll_Calculation_Employee_Ex = new HashSet<tbl_Payroll_Calculation_Employee_Ex>();
            this.tbl_Payroll_Calculation_Employee = new HashSet<tbl_Payroll_Calculation_Employee>();
            this.tbl_Payroll_Variable = new HashSet<tbl_Payroll_Variable>();
            this.tbl_Tax = new HashSet<tbl_Tax>();
            this.tbl_Employee_Document = new HashSet<tbl_Employee_Document>();
            this.tbl_User_Mobile = new HashSet<tbl_User_Mobile>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Employee_No { get; set; }
        public string Salutation { get; set; }
        public string Full_Name { get; set; }
        public string Place_Of_Birth { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Mother_Maiden_Name { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string Blood_Type { get; set; }
        public string Nationality { get; set; }
        public string Marital_Status { get; set; }
        public Nullable<int> Number_Of_Children { get; set; }
        public string Education { get; set; }
        public string Last_Education { get; set; }
        public string BPJS_TK_NPP { get; set; }
        public string BPJS_Health_NPP { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<System.Guid> Workflow_Status_ID { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public string Path_Image { get; set; }
        public Nullable<System.Guid> Face_Recognation_Id { get; set; }
    
        public virtual ICollection<tbl_Additional_Payroll> tbl_Additional_Payroll { get; set; }
        public virtual ICollection<tbl_Compensation_Benefit> tbl_Compensation_Benefit { get; set; }
        public virtual ICollection<tbl_Payroll_Transaction> tbl_Payroll_Transaction { get; set; }
        public virtual ICollection<tbl_Payroll_Slip_Employee> tbl_Payroll_Slip_Employee { get; set; }
        public virtual ICollection<tbl_Employee_Appointment> tbl_Employee_Appointment { get; set; }
        public virtual ICollection<tbl_Employee_Family> tbl_Employee_Family { get; set; }
        public virtual ICollection<tbl_Employee_ID_Information> tbl_Employee_ID_Information { get; set; }
        public virtual ICollection<tbl_Employee_Payment> tbl_Employee_Payment { get; set; }
        public virtual tbl_Organization tbl_Organization { get; set; }
        public virtual ICollection<tbl_Payroll_Calculation_Employee_Ex> tbl_Payroll_Calculation_Employee_Ex { get; set; }
        public virtual ICollection<tbl_Payroll_Calculation_Employee> tbl_Payroll_Calculation_Employee { get; set; }
        public virtual ICollection<tbl_Payroll_Variable> tbl_Payroll_Variable { get; set; }
        public virtual ICollection<tbl_Tax> tbl_Tax { get; set; }
        public virtual ICollection<tbl_Employee_Document> tbl_Employee_Document { get; set; }
        public virtual ICollection<tbl_User_Mobile> tbl_User_Mobile { get; set; }
    }
}
