//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Menu_Restriction
    {
        public tbl_Menu_Restriction()
        {
            this.tbl_Menu_Function_Restriction = new HashSet<tbl_Menu_Function_Restriction>();
        }
    
        public System.Guid id { get; set; }
        public string Menu_Restriction_Code { get; set; }
        public string Menu_Restriction_Description { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
    
        public virtual ICollection<tbl_Menu_Function_Restriction> tbl_Menu_Function_Restriction { get; set; }
    }
}
