//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee_Appointment
    {
        public tbl_Employee_Appointment()
        {
            this.tbl_Appointment_Contract_Information = new HashSet<tbl_Appointment_Contract_Information>();
            this.tbl_Appointment_Department = new HashSet<tbl_Appointment_Department>();
            this.tbl_Appointment_Division = new HashSet<tbl_Appointment_Division>();
            this.tbl_Appointment_Grade = new HashSet<tbl_Appointment_Grade>();
            this.tbl_Appointment_Position = new HashSet<tbl_Appointment_Position>();
            this.tbl_Appointment_Status_Information = new HashSet<tbl_Appointment_Status_Information>();
            this.tbl_Appointment_Work_Location = new HashSet<tbl_Appointment_Work_Location>();
            this.tbl_Appointment_Working_Time = new HashSet<tbl_Appointment_Working_Time>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid Employee_ID { get; set; }
        public Nullable<System.DateTime> Date_Of_Hire { get; set; }
        public Nullable<System.DateTime> Join_Date { get; set; }
        public Nullable<System.DateTime> End_Date_of_Probation { get; set; }
        public string Old_Employee_Number { get; set; }
        public string Cost_Center { get; set; }
        public string Resign_Reason { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public string Deputation { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
    
        public virtual ICollection<tbl_Appointment_Contract_Information> tbl_Appointment_Contract_Information { get; set; }
        public virtual ICollection<tbl_Appointment_Department> tbl_Appointment_Department { get; set; }
        public virtual ICollection<tbl_Appointment_Division> tbl_Appointment_Division { get; set; }
        public virtual ICollection<tbl_Appointment_Grade> tbl_Appointment_Grade { get; set; }
        public virtual ICollection<tbl_Appointment_Position> tbl_Appointment_Position { get; set; }
        public virtual ICollection<tbl_Appointment_Status_Information> tbl_Appointment_Status_Information { get; set; }
        public virtual ICollection<tbl_Appointment_Work_Location> tbl_Appointment_Work_Location { get; set; }
        public virtual ICollection<tbl_Appointment_Working_Time> tbl_Appointment_Working_Time { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
