//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Branch_List_Of_Bank
    {
        public tbl_Branch_List_Of_Bank()
        {
            this.tbl_Employee_Payment = new HashSet<tbl_Employee_Payment>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> List_Of_Bank_ID { get; set; }
        public string Branch_Code { get; set; }
        public string Branch_Name { get; set; }
        public string Remarks { get; set; }
    
        public virtual tbl_List_Of_Bank tbl_List_Of_Bank { get; set; }
        public virtual ICollection<tbl_Employee_Payment> tbl_Employee_Payment { get; set; }
    }
}
