//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee_Payroll_Component
    {
        public tbl_Employee_Payroll_Component()
        {
            this.tbl_Compensation_Benefit = new HashSet<tbl_Compensation_Benefit>();
            this.tbl_Employee_Payroll_Component_Effective = new HashSet<tbl_Employee_Payroll_Component_Effective>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid Employee_id { get; set; }
        public string Organization_Payroll_Component_Code { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> Tax_Deduction { get; set; }
        public string Tax_Policy { get; set; }
        public Nullable<bool> Is_Generated { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public string Authorized_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
    
        public virtual ICollection<tbl_Compensation_Benefit> tbl_Compensation_Benefit { get; set; }
        public virtual ICollection<tbl_Employee_Payroll_Component_Effective> tbl_Employee_Payroll_Component_Effective { get; set; }
    }
}
