//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payroll_Calculation_Employee
    {
        public System.Guid id { get; set; }
        public System.Guid Payroll_Calculation_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Employment_Status { get; set; }
        public string Employee_Status { get; set; }
        public Nullable<System.DateTime> Status_Effective_Date { get; set; }
        public Nullable<short> Employee_Working_Day { get; set; }
        public string Tax_Number { get; set; }
        public string PTKP { get; set; }
        public bool Is_Success { get; set; }
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public string Salary_Tax_Policy { get; set; }
    
        public virtual tbl_Payroll_Calculation tbl_Payroll_Calculation { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
