//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Report_Tax_Summary
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Organization_Id { get; set; }
        public Nullable<System.Guid> Tax_Period_Id { get; set; }
        public Nullable<int> Correction { get; set; }
        public Nullable<System.Guid> Employee_Id { get; set; }
        public string Employment_Status { get; set; }
        public string Kode_Objek_Wajib_Pajak { get; set; }
        public Nullable<double> Sum_Bruto { get; set; }
        public Nullable<double> Sum_Tax { get; set; }
        public string Head_Tax_Id { get; set; }
        public string Batch { get; set; }
    }
}
