//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Attendance_Request_Details
    {
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> Date_Request { get; set; }
        public Nullable<System.DateTime> Date_Authorize { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> Reporter_ID { get; set; }
        public string Reporter_No { get; set; }
        public string Reporter_Name { get; set; }
        public System.DateTime Day_Time_In { get; set; }
        public System.DateTime Day_Time_Out { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public string Authorized_Remark { get; set; }
        public Nullable<System.Guid> Reportto_ID { get; set; }
        public string Reportto_No { get; set; }
        public string Reportto_Name { get; set; }
        public string str_Date_Request { get; set; }
        public string str_Date { get; set; }
        public string str_Time_IN { get; set; }
        public string str_Time_OUT { get; set; }
        public string str_status { get; set; }
        public string str_Date_Authorize { get; set; }
        public string str_Employee { get; set; }
    }
}
