//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_appointment_information
    {
        public System.Guid Employee_Appointment_Id { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Employment_Status { get; set; }
        public string Employee_Status { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
        public Nullable<System.DateTime> Date_Of_Hire { get; set; }
        public Nullable<System.DateTime> Join_Date { get; set; }
        public string Old_Employee_Number { get; set; }
        public Nullable<System.DateTime> End_Date_of_Probation { get; set; }
        public string Work_Location { get; set; }
        public Nullable<System.DateTime> Work_Location_Effective_Date { get; set; }
        public string Record_Status { get; set; }
        public string Position_Code { get; set; }
        public string Position_Description { get; set; }
        public Nullable<System.DateTime> Position_Effective_Date { get; set; }
        public string Division_Code { get; set; }
        public string Division_Description { get; set; }
        public Nullable<System.DateTime> Division_Effective_Date { get; set; }
        public string Department_Code { get; set; }
        public string Department_Description { get; set; }
        public Nullable<System.DateTime> Department_Effective_Date { get; set; }
        public string Grade_Code { get; set; }
        public string Grade_Description { get; set; }
        public Nullable<System.DateTime> Grade_Effective_Date { get; set; }
        public string Cost_Center { get; set; }
        public string Deputation { get; set; }
        public string Resign_Reason { get; set; }
        public string Working_Time_Code { get; set; }
        public string Working_Time_Description { get; set; }
        public Nullable<System.DateTime> Working_Start_Date { get; set; }
        public Nullable<System.DateTime> Working_End_Date { get; set; }
        public string Contract_No { get; set; }
        public Nullable<System.DateTime> Contract_Start_Date { get; set; }
        public Nullable<System.DateTime> Contract_End_Date { get; set; }
        public string Authorize_Status { get; set; }
        public Nullable<System.Guid> id { get; set; }
    }
}
