//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Attendance_Summary_Sync
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public string Cut_Off_Attendance { get; set; }
        public Nullable<System.DateTime> Cut_Off_Time_Start { get; set; }
        public Nullable<System.DateTime> Cut_Off_Time_End { get; set; }
        public Nullable<long> Last_Upload_Number { get; set; }
        public string Last_Uploaded_By { get; set; }
        public Nullable<System.DateTime> Last_Uploaded_Datetime { get; set; }
        public string Path_File { get; set; }
        public Nullable<int> Last_Synced_Status { get; set; }
        public Nullable<int> Last_Synced_Row { get; set; }
        public Nullable<int> Last_Synced_Success { get; set; }
        public Nullable<int> Last_Sync_Error { get; set; }
        public Nullable<int> Last_Sync_Warning { get; set; }
        public string Device_Finger { get; set; }
    }
}
