//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Attendance_Finger_ID
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> User_Id { get; set; }
        public string Finger_ID { get; set; }
        public System.Guid Organization_ID { get; set; }
        public System.Guid Employee_Id { get; set; }
        public string Employee_No { get; set; }
        public string Full_Name { get; set; }
        public string Organization_Name { get; set; }
    }
}
