//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Additional_Payroll
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public string Employee_No { get; set; }
        public Nullable<System.DateTime> Tax_Period { get; set; }
        public string Payroll_Period { get; set; }
        public string Employee_Name { get; set; }
        public string Record_Status { get; set; }
        public string Authorize_Status { get; set; }
        public string Additional_Remark { get; set; }
        public string Additional_Upload_No { get; set; }
        public string Employee_Status { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Category { get; set; }
    }
}
