//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Base_Location
    {
        public System.Guid Appointment_Work_Location_Id { get; set; }
        public System.Guid Employee_Appointment_Id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Full_Name { get; set; }
        public System.Guid Employee_Id { get; set; }
        public System.Guid HeadOffice_Branch_Location_Id { get; set; }
        public string Work_Location { get; set; }
        public string HO_Branch_TAX_ID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<decimal> Range { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public System.Guid Base_Location_Id { get; set; }
        public string Base_Location_Name { get; set; }
    }
}
