//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Calculation_Tax_All
    {
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public Nullable<int> Run { get; set; }
        public System.Guid Calculation_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Type { get; set; }
        public string Employee_Status { get; set; }
        public string Employment_Status { get; set; }
        public string Salary_Tax_policy { get; set; }
        public Nullable<int> Payroll_year { get; set; }
        public Nullable<int> Payroll_Month { get; set; }
        public string Tax_ID_Status_Change { get; set; }
        public string Tax_ID_Status_Change_After { get; set; }
        public string PTKP { get; set; }
        public string Organization_Tax_Number { get; set; }
        public string Organization_ID { get; set; }
        public string Calculation_Flag { get; set; }
        public string payment_no { get; set; }
        public string Tax_Policy { get; set; }
        public string Month_Date_Of_Hire { get; set; }
        public string First_Payroll_Month { get; set; }
        public string End_Payroll_Month { get; set; }
        public string Current_Payroll_Month { get; set; }
        public int Pembetulan { get; set; }
        public string Tax_Allowance { get; set; }
        public string Tax_Allowance_On_Bonus { get; set; }
        public string Annual_Factor { get; set; }
        public string Gross_Salary_Regular { get; set; }
        public string Gross_Salary { get; set; }
        public string Month_Income_Regular { get; set; }
        public string Income_Per_Year { get; set; }
        public string Total_Income_Regular { get; set; }
        public string Tax_Deduction_Regular { get; set; }
        public string Cost_Parameter_Max_Cost { get; set; }
        public string Cost_Parameter_Percentage { get; set; }
        public string Functional_Cost_Constant { get; set; }
        public string Functional_Cost { get; set; }
        public string Non_Taxable_Income { get; set; }
        public string EmpPayCompAsTaxDeduction { get; set; }
        public string Total_Tax_Deduction_Regular { get; set; }
        public string Netto { get; set; }
        public string Netto_Annualized { get; set; }
        public string Previous_Netto { get; set; }
        public string Taxable_Income_Regular { get; set; }
        public string Taxable_Income_Regular_Round { get; set; }
        public string Tax_Bracket_Regular_And_Tax_Regular { get; set; }
        public string Total_Tax_Calculation_Regular { get; set; }
        public string Previous_Tax { get; set; }
        public string TaxDueUpToCurrPeriodRegular { get; set; }
        public string Tax_Payment_Regular { get; set; }
        public string Tax21PerMonthRegular { get; set; }
        public string TaxForNetRegularComponent { get; set; }
        public string Tax_Allowance2nd { get; set; }
        public string Bonus_Non_Regular_Income { get; set; }
        public string Total_Income { get; set; }
        public string Functional_Cost_on_Bonus { get; set; }
        public string Total_Tax_Deduction { get; set; }
        public string Netto_2 { get; set; }
        public string Netto_2_Irragular { get; set; }
        public string Netto_Annualized_2 { get; set; }
        public string Taxable_Income { get; set; }
        public string Taxable_Income_Round { get; set; }
        public string Tax_Bracket_And_Tax { get; set; }
        public string Total_Tax_Calculation { get; set; }
        public string TaxDueUpToCurrPeriod { get; set; }
        public string Tax_Payment { get; set; }
        public string Tax21PerMonth { get; set; }
        public string B1TaxForNetIregularComponent { get; set; }
        public string TaxAllowanceOnBonus2nd { get; set; }
        public string Tax { get; set; }
        public string Tax_On_Bonus { get; set; }
        public string Tax_Regular_Borne_By_Company { get; set; }
        public string Tax_Irregular_Borne_By_Company { get; set; }
        public string Net_Salary { get; set; }
        public string Non_Taxable { get; set; }
        public string Total_Deduction { get; set; }
        public string Tax_Refund { get; set; }
        public string Take_Home_Pay { get; set; }
        public string First_Tax_Period_Month { get; set; }
        public string Current_Tax_Period_Month { get; set; }
        public string First_Payment { get; set; }
        public string Cumulative_Gross_Income { get; set; }
        public string Taxable_Income_Rounding { get; set; }
        public string Calculate_Tax_Bracket_and_Tax { get; set; }
        public string Tax_Due_UpTo_Curr_Tax_Period_Month { get; set; }
        public string Tax_Paid { get; set; }
        public string Tax_Per_Payment { get; set; }
        public string Check_Tax_Allowance { get; set; }
        public string Total_Tax_Allowance { get; set; }
        public string Tax_Borne_By_Company { get; set; }
        public string Check_Number_of_Payment { get; set; }
        public string Total_Gross_Salary { get; set; }
        public string Tax_Per_Period { get; set; }
        public string Total_Tax_Borne_By_Company { get; set; }
        public string Net_Income_Non_Permanent { get; set; }
        public string Total_Addition { get; set; }
        public string Tax_Refund_PTKP { get; set; }
        public string Tax_Refund_NPWP { get; set; }
        public string Tax_Refund_Amount { get; set; }
        public string Total_Tax_Refund { get; set; }
        public string Take_Home_Pay_Non_Permanent { get; set; }
        public string End_Tax_Period_Month { get; set; }
        public string Tax_allowance_On_Final_Payment { get; set; }
        public string Gross_Final { get; set; }
        public string Cumulative_Gross_Final { get; set; }
        public string Tax_Due_Upto_Current_Tax_Period_Month { get; set; }
        public string Tax_On_Final_Payment_Per_Payment { get; set; }
        public string Total_Tax_Allowance_On_Final_Payment { get; set; }
        public string Tax_On_Final_Borne_By_Company { get; set; }
        public string Total_Gross_Final { get; set; }
        public string Tax_On_Final_Payment_Per_Period { get; set; }
        public string Total_Tax_On_Final_Borne_By_Company { get; set; }
        public string Net_Income_Final { get; set; }
        public string Total_Deduction_Final { get; set; }
        public string Total_Addition_Final { get; set; }
        public string Tax_Refund_Final { get; set; }
        public string Take_Home_Pay_Final { get; set; }
        public string Check_Tax_allowance_On_Final_Payment { get; set; }
    }
}
