//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Chat_Account
    {
        public System.Guid id { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone_No { get; set; }
        public Nullable<int> Account_Status { get; set; }
        public bool IsAdmin { get; set; }
        public string Company_Name { get; set; }
        public Nullable<int> Msg { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
    }
}
