//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Chat_Log
    {
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> Log_dt { get; set; }
        public string Type { get; set; }
        public string User_From { get; set; }
        public string Name_From { get; set; }
        public string User_To { get; set; }
        public string Name_To { get; set; }
        public string Chat { get; set; }
        public string Image { get; set; }
        public string Version_ID { get; set; }
        public Nullable<int> Chat_Status { get; set; }
    }
}
