//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Compensation_Benefit
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public System.Guid Employee { get; set; }
        public string Employee_No { get; set; }
        public string Full_Name { get; set; }
        public string Employee_ID { get; set; }
        public string Type_Compensation_Benefit { get; set; }
        public string Organization_Payroll_Component_Code { get; set; }
        public string Description { get; set; }
        public System.Guid Component_Linkage_ID { get; set; }
        public string Component_Linkage { get; set; }
        public string Component_Group { get; set; }
        public string Currency { get; set; }
        public decimal Budget { get; set; }
        public string Period { get; set; }
        public string Upload_Number { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
    }
}
