//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Calculation_Transaction
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Organization_Name { get; set; }
        public string Batch { get; set; }
        public int Tax_Year { get; set; }
        public System.DateTime Tax_Peroid_From { get; set; }
        public System.DateTime Tax_Peroid_To { get; set; }
        public System.DateTime Tax_Period { get; set; }
        public System.DateTime Period_Start_Date { get; set; }
        public System.DateTime Period_End_Date { get; set; }
        public Nullable<int> Run { get; set; }
        public string Employee_No { get; set; }
        public string Full_Name { get; set; }
        public string Employment_Status { get; set; }
        public string Employee_Status { get; set; }
        public Nullable<System.DateTime> Status_Effective_Date { get; set; }
        public Nullable<short> Employee_Working_Day { get; set; }
        public string Tax_Number { get; set; }
        public string PTKP { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public string Payroll_Component_Code { get; set; }
        public string Payroll_Component_Description { get; set; }
        public string Formula { get; set; }
        public string Component_Payroll { get; set; }
        public string Component_Value { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Calculate_Amount { get; set; }
        public Nullable<double> Additional_Payroll { get; set; }
        public Nullable<double> Additional_Income { get; set; }
        public Nullable<double> Original_Amount { get; set; }
        public Nullable<double> Rounding_Amount { get; set; }
        public string Calculation_Basic { get; set; }
        public Nullable<bool> Is_Prorate_New_Resign { get; set; }
        public Nullable<bool> Is_Prorate { get; set; }
        public Nullable<double> Exchange_Rate { get; set; }
        public string Taxable_Type { get; set; }
        public string Frequency { get; set; }
        public string Tax_Policy { get; set; }
        public Nullable<bool> Tax_Deduction { get; set; }
        public string Prorate_Base { get; set; }
        public Nullable<bool> isSuccess { get; set; }
        public string Reason { get; set; }
        public string Sign { get; set; }
        public System.Guid Payroll_Calculation_ID { get; set; }
    }
}
