//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_component_formula
    {
        public Nullable<System.Guid> employee_id { get; set; }
        public string organization_payroll_component_code { get; set; }
        public string description { get; set; }
        public string component_group { get; set; }
        public string Amount_Type { get; set; }
        public string Calculation_Basic { get; set; }
        public bool Is_New_Join { get; set; }
        public bool Is_Prorate { get; set; }
        public string Prorate_Base { get; set; }
        public string formula { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
    }
}
