//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Download_Employee_Payroll_Component
    {
        public System.Guid id { get; set; }
        public System.Guid Employee_id { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public string Employee_No { get; set; }
        public string Full_Name { get; set; }
        public string Organization_Payroll_Component_Code { get; set; }
        public string Organization_Payroll_Component_Code_Description { get; set; }
        public string Currency { get; set; }
        public string Currency_Description { get; set; }
        public string Component_Group_Description { get; set; }
        public string Taxable_Type { get; set; }
        public string Tax_Deduction { get; set; }
        public string Tax_Policy { get; set; }
        public string Frequency { get; set; }
        public string Amount_Type { get; set; }
        public string Calculation_Basic { get; set; }
        public string Prorate_Base { get; set; }
        public bool Is_New_Join { get; set; }
        public bool Is_Prorate { get; set; }
        public string Sign { get; set; }
        public string Account { get; set; }
        public string Db_or_Cr { get; set; }
        public string SPT_Code { get; set; }
        public string Remark { get; set; }
        public string Status_Code { get; set; }
        public string Authorize_Status { get; set; }
        public Nullable<bool> Is_Generated { get; set; }
        public Nullable<System.DateTime> Start_Date1 { get; set; }
        public Nullable<System.DateTime> End_Date1 { get; set; }
        public string Formula1 { get; set; }
        public Nullable<System.DateTime> Start_Date2 { get; set; }
        public Nullable<System.DateTime> End_Date2 { get; set; }
        public string Formula2 { get; set; }
        public Nullable<System.DateTime> Start_Date3 { get; set; }
        public Nullable<System.DateTime> End_Date3 { get; set; }
        public string Formula3 { get; set; }
        public Nullable<System.DateTime> Start_Date4 { get; set; }
        public Nullable<System.DateTime> End_Date4 { get; set; }
        public string Formula4 { get; set; }
        public Nullable<System.DateTime> Start_Date5 { get; set; }
        public Nullable<System.DateTime> End_Date5 { get; set; }
        public string Formula5 { get; set; }
        public Nullable<System.DateTime> Start_Date6 { get; set; }
        public Nullable<System.DateTime> End_Date6 { get; set; }
        public string Formula6 { get; set; }
        public Nullable<System.DateTime> Start_Date7 { get; set; }
        public Nullable<System.DateTime> End_Date7 { get; set; }
        public string Formula7 { get; set; }
        public Nullable<System.DateTime> Start_Date8 { get; set; }
        public Nullable<System.DateTime> End_Date8 { get; set; }
        public string Formula8 { get; set; }
        public Nullable<System.DateTime> Start_Date9 { get; set; }
        public Nullable<System.DateTime> End_Date9 { get; set; }
        public string Formula9 { get; set; }
        public Nullable<System.DateTime> Start_Date10 { get; set; }
        public Nullable<System.DateTime> End_Date10 { get; set; }
        public string Formula10 { get; set; }
    }
}
