//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Employee_Approval
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public string Employee_ID_Number { get; set; }
        public string Full_Name { get; set; }
        public Nullable<System.Guid> Supervisor_ID { get; set; }
        public string Supervisor_ID_Number { get; set; }
        public string Supervisor_Name { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
    }
}
