//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Employee_Leave_Entitlement_Summary
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_Id { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_DateTime { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Authorized_DateTime { get; set; }
        public string Authorized_By { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public string Leave_Type { get; set; }
        public Nullable<double> Entitlement { get; set; }
        public Nullable<System.DateTime> Period_Start { get; set; }
        public Nullable<System.DateTime> Period_End { get; set; }
        public string Description { get; set; }
        public string Period { get; set; }
    }
}
