//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Employee_Tax_Status
    {
        public System.Guid id { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Employee_No { get; set; }
        public string Full_Name { get; set; }
        public string Organization_Code { get; set; }
        public string Organization_Name { get; set; }
        public string PTKP { get; set; }
        public string Year_Status { get; set; }
        public string Tax_No { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
    }
}
