//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Employee_Payslip_Summary
    {
        public long Id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public Nullable<System.DateTime> Period_Start_Date { get; set; }
        public Nullable<System.DateTime> Period_End_Date { get; set; }
        public Nullable<System.DateTime> Generate_Date { get; set; }
        public string Payslip_Distribution { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public string Employee_No { get; set; }
        public string Email_Address { get; set; }
        public string Generation_Number { get; set; }
        public string Payslip_Status { get; set; }
        public string Version { get; set; }
        public string Payslip_Url { get; set; }
    }
}
