//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Employee_Appointment_WorkingTime
    {
        public System.Guid id { get; set; }
        public System.Guid Employee_Id { get; set; }
        public string Employee_No { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Working_Time_Code { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Working_Time_Description { get; set; }
        public string Working_Day { get; set; }
        public string Base_Working_Day { get; set; }
        public Nullable<int> Base_Fix { get; set; }
    }
}
