//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Employee_Component_Formula
    {
        public System.Guid id { get; set; }
        public System.Guid Employee_id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Organization_Payroll_Component_Code { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Formula { get; set; }
        public string Amount_Type { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> Tax_Deduction { get; set; }
        public string Tax_Policy { get; set; }
        public string Remark { get; set; }
        public string Component_Group { get; set; }
        public string Taxable_Type { get; set; }
        public string Frequency { get; set; }
    }
}
