//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Login_Epayslip
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Organization_Code { get; set; }
        public string Organization_Name { get; set; }
        public string Employee_No { get; set; }
        public string Full_Name { get; set; }
        public string Payslip_Distribution { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Is_HR_User { get; set; }
        public Nullable<bool> Is_Change_Password { get; set; }
        public string Coorporate_Email_Address { get; set; }
        public string Personal_Email_Address { get; set; }
        public string Security_Code { get; set; }
        public Nullable<System.DateTime> Security_Code_DateTime { get; set; }
    }
}
