//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Leave_Employee
    {
        public System.Guid id { get; set; }
        public System.Guid Employee_Leave_Entitlement_ID { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public string Leave_Type { get; set; }
        public Nullable<System.DateTime> Period_Start { get; set; }
        public Nullable<System.DateTime> Period_End { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<double> Entitlement { get; set; }
        public Nullable<double> Used { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
    }
}
