//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Menu_Function
    {
        public System.Guid id { get; set; }
        public System.Guid Menu_ID { get; set; }
        public string Menu_Code { get; set; }
        public string Menu_Name { get; set; }
        public Nullable<System.Guid> Function_ID { get; set; }
        public string Function_Code { get; set; }
        public string Function_Description { get; set; }
    }
}
