//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_New_BPJS_Manpower
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Employee_No { get; set; }
        public Nullable<System.DateTime> Date_Of_Hire { get; set; }
        public string Full_Name { get; set; }
        public string Education { get; set; }
        public string Residential_Phone_No { get; set; }
        public string Office_Phone_No { get; set; }
        public string Mobile_Phone_No { get; set; }
        public string Personal_Email_Address { get; set; }
        public string Place_Of_Birth { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Mother_Maiden_Name { get; set; }
        public string ID_Type { get; set; }
        public string ID_Number { get; set; }
        public Nullable<System.DateTime> Expired_Date { get; set; }
        public string Gender { get; set; }
        public string Coorporate_Email_Address { get; set; }
        public string Marital_Status { get; set; }
        public string Blood_Type { get; set; }
        public string Bank_Code { get; set; }
        public string Branch_Name { get; set; }
        public string Employee_Bank_Account { get; set; }
        public string Account_Name { get; set; }
        public string Nationality { get; set; }
        public string Address { get; set; }
        public string Zip_Code { get; set; }
        public string Relationship { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
    }
}
