//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Orgnization_Type
    {
        public string Organization_Code { get; set; }
        public string Organization_Name { get; set; }
        public string Organization_Type_Code { get; set; }
        public Nullable<bool> Auto_Generate_Employee_No { get; set; }
        public Nullable<int> Status_Code { get; set; }
    }
}
