//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Payroll_Payment_Details
    {
        public long Id { get; set; }
        public string Batch { get; set; }
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public string Payroll_Period { get; set; }
        public Nullable<int> Run { get; set; }
        public System.Guid Organization_ID { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public string Employee_No { get; set; }
        public string Full_Name { get; set; }
        public int Beneficiary_Status { get; set; }
        public string Title { get; set; }
        public string Payment_Bank_Code { get; set; }
        public string Employee_Bank_Account { get; set; }
        public string Employee_Bank_Code { get; set; }
        public string Currency_Code { get; set; }
        public string Employee_Account_Name { get; set; }
        public Nullable<double> Percentage { get; set; }
        public string Beneficiary_BI_Code { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Beneficiary_Branch_Code { get; set; }
        public string Branch_Name { get; set; }
        public string Personal_Email_Address { get; set; }
        public string Beneficiary_Address { get; set; }
        public Nullable<double> Take_Home_Pay { get; set; }
        public Nullable<double> Employee_Salary_Transferred { get; set; }
    }
}
