//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Payroll_Calculation_Period
    {
        public Nullable<System.Guid> ID { get; set; }
        public System.Guid Organization_ID { get; set; }
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public string Period { get; set; }
        public Nullable<int> Run { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> Period_Start_Date { get; set; }
        public Nullable<System.DateTime> Period_End_Date { get; set; }
        public Nullable<System.DateTime> Tax_Period { get; set; }
    }
}
