//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payroll_cal_np
    {
        public System.Guid Calculation_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Payroll_Component_Code { get; set; }
        public Nullable<int> Payroll_Month { get; set; }
        public Nullable<int> Payroll_Year { get; set; }
        public string Trx_Date { get; set; }
        public Nullable<int> Pembetulan { get; set; }
        public Nullable<int> Tax_Allowance { get; set; }
        public Nullable<int> First_Payment { get; set; }
        public Nullable<int> Gross_Salary { get; set; }
        public Nullable<int> Cumulative_Gross_Income { get; set; }
        public Nullable<int> Non_Taxable_Income { get; set; }
        public Nullable<int> Taxable_Income { get; set; }
        public Nullable<int> Taxable_Income_Rounding { get; set; }
        public Nullable<int> Calculate_Tax_Bracket_and_Tax { get; set; }
        public Nullable<int> Total_Tax_Calculation { get; set; }
        public Nullable<int> Tax_Due_UpTo_Curr_Tax_Period_Month { get; set; }
        public Nullable<int> Tax_Paid { get; set; }
        public Nullable<int> Tax_Per_Payment { get; set; }
        public Nullable<int> Total_Tax_Allowance { get; set; }
        public Nullable<int> Tax_Borne_By_Company { get; set; }
        public Nullable<int> Total_Gross_Salary { get; set; }
        public Nullable<int> Tax_Per_Period { get; set; }
        public Nullable<int> Total_Tax_Borne_By_Company { get; set; }
        public Nullable<int> Net_Income_Non_Permanent { get; set; }
        public Nullable<int> Total_Deduction { get; set; }
        public Nullable<int> Total_Addition { get; set; }
        public Nullable<int> Tax_Refund_PTKP { get; set; }
        public Nullable<int> Tax_Refund_NPWP { get; set; }
        public Nullable<int> Tax_Refund_Amount { get; set; }
        public Nullable<int> Total_Tax_Refund { get; set; }
        public Nullable<int> Take_Home_Pay_Non_Permanent { get; set; }
    }
}
