//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Payroll_Slip_Description_Employee
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Organization_Code { get; set; }
        public string Organization_Name { get; set; }
        public string Logo { get; set; }
        public string Employee_No { get; set; }
        public string Full_Name { get; set; }
        public string Tax_No { get; set; }
        public string Struktur { get; set; }
        public string Description { get; set; }
        public string Tax_Status { get; set; }
        public string Department { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
    }
}
