//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PayrollSlip_List_Bank
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Employee_No { get; set; }
        public string Full_Name { get; set; }
        public string Employee_Bank_Account { get; set; }
        public string Bank_Code { get; set; }
        public string Description { get; set; }
        public string Branch_Code { get; set; }
        public string Branch_Name { get; set; }
        public string Currency_Code { get; set; }
        public string Account_Name { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
    }
}
