//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payroll_cal_sp
    {
        public System.Guid Calculation_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Payroll_Component_Code { get; set; }
        public Nullable<int> Payroll_Month { get; set; }
        public Nullable<int> Payroll_Year { get; set; }
        public string Trx_Date { get; set; }
        public Nullable<int> Pembetulan { get; set; }
        public Nullable<double> First_Tax_Period_Month { get; set; }
        public Nullable<double> End_Tax_Period_Month { get; set; }
        public Nullable<double> Current_Tax_Period_Month { get; set; }
        public Nullable<double> First_Payment { get; set; }
        public Nullable<double> Gross_Final { get; set; }
        public Nullable<double> Cumulative_Gross_Final { get; set; }
        public Nullable<double> Taxable_Income { get; set; }
        public Nullable<double> Taxable_Income_Rounding { get; set; }
        public Nullable<double> Calculate_Tax_Bracket_And_Tax { get; set; }
        public Nullable<double> Total_Tax_Calculation { get; set; }
        public Nullable<double> Tax_Due_Upto_Current_Tax_Period_Month { get; set; }
        public Nullable<double> Tax_Paid { get; set; }
        public Nullable<double> Tax_On_Final_Payment_Per_Payment { get; set; }
        public Nullable<double> Tax_allowance_On_Final_Payment { get; set; }
        public Nullable<double> Total_Tax_Allowance_On_Final_Payment { get; set; }
        public Nullable<double> Tax_On_Final_Borne_By_Company { get; set; }
        public Nullable<double> Check_Number_Of_Payment { get; set; }
        public Nullable<double> Total_Gross_Final { get; set; }
        public Nullable<double> Tax_On_Final_Payment_Per_Period { get; set; }
        public Nullable<double> Total_Tax_On_Final_Borne_By_Company { get; set; }
        public Nullable<double> Net_Income_Final { get; set; }
        public Nullable<double> Total_Deduction_Final { get; set; }
        public Nullable<double> Total_Addition_Final { get; set; }
        public Nullable<double> Tax_Refund_Final { get; set; }
        public Nullable<double> Take_Home_Pay_Final { get; set; }
    }
}
