//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Payroll_Detail_Calculation
    {
        public System.Guid id { get; set; }
        public System.Guid Payroll_Calculation_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Employee_No { get; set; }
        public string Full_Name { get; set; }
        public string Is_Success { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Take_Home_Pay { get; set; }
    }
}
