//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Payroll_Aditional
    {
        public long Id { get; set; }
        public System.Guid Additional_Payroll_Id { get; set; }
        public string Batch_No { get; set; }
        public Nullable<int> Run { get; set; }
        public int Pembetulan { get; set; }
    }
}
