//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Report_Employee_Tax_Component
    {
        public System.Guid id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public Nullable<int> Run { get; set; }
        public string Payroll_Component_Code { get; set; }
        public string Payroll_Component_Description { get; set; }
        public System.Guid Employee_ID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Taxable_Type { get; set; }
        public Nullable<bool> Tax_Deduction { get; set; }
        public System.Guid Calculation_ID { get; set; }
        public Nullable<int> SPT_Code { get; set; }
        public Nullable<System.Guid> Payroll_Calculation_ID { get; set; }
        public string Component_Group { get; set; }
        public string Salary_Tax_Policy { get; set; }
    }
}
