//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Run_Closing
    {
        public System.Guid Payroll_Calculation_ID { get; set; }
        public int Year { get; set; }
        public System.Guid Organization_ID { get; set; }
        public Nullable<int> month { get; set; }
        public string Calculation_Type { get; set; }
    }
}
