//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_report_tax_calculation
    {
        public System.Guid Calculation_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public Nullable<int> Order { get; set; }
        public string Calculation_Component { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
        public string Employee_No { get; set; }
        public string Full_Name { get; set; }
        public Nullable<int> Payroll_Month { get; set; }
        public Nullable<int> Payroll_Year { get; set; }
    }
}
