//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Report_Employee_JKK
    {
        public System.DateTime Tax_Period { get; set; }
        public System.DateTime Period_Start_Date { get; set; }
        public System.DateTime Period_End_Date { get; set; }
        public Nullable<System.Guid> Payroll_Calculation_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public string Component_Group { get; set; }
        public string Formula { get; set; }
        public string Taxable_Type { get; set; }
        public Nullable<double> Rounding_Amount { get; set; }
    }
}
