//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Report_Summary_History
    {
        public long Id { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Organization_Name { get; set; }
        public string Component_Description { get; set; }
        public string Component_Tax_Policy { get; set; }
        public string Bonus { get; set; }
        public string Non_Taxable_Income { get; set; }
        public Nullable<int> Year { get; set; }
        public string Gross_Salary { get; set; }
        public string TAX { get; set; }
        public Nullable<int> Gross_Final { get; set; }
        public Nullable<int> Tax_On_Final { get; set; }
        public string Net_Salary { get; set; }
        public Nullable<double> January { get; set; }
        public Nullable<double> February { get; set; }
        public Nullable<double> March { get; set; }
        public Nullable<double> April { get; set; }
        public Nullable<double> May { get; set; }
        public Nullable<double> June { get; set; }
        public Nullable<double> July { get; set; }
        public Nullable<double> August { get; set; }
        public Nullable<double> September { get; set; }
        public Nullable<double> October { get; set; }
        public Nullable<double> November { get; set; }
        public Nullable<double> December { get; set; }
    }
}
