//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Report_Setting
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Organization_id { get; set; }
        public string Payroll_Report_Code { get; set; }
        public string Description { get; set; }
        public string Report_Format { get; set; }
        public string Record_Status { get; set; }
        public string Authorize_Status { get; set; }
        public string Report_Layout { get; set; }
        public string Target { get; set; }
    }
}
