//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SessionKey
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> User_Id { get; set; }
        public string KeyPush { get; set; }
        public string Salt { get; set; }
        public System.Guid Employee_Id { get; set; }
        public Nullable<bool> Is_login { get; set; }
        public string Device { get; set; }
    }
}
