//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Trx_Bank_Transfer
    {
        public long Id { get; set; }
        public System.Guid Trx_Bank_Transfer_ID { get; set; }
        public Nullable<System.Guid> Organization_ID { get; set; }
        public string Organization_Name { get; set; }
        public Nullable<int> Run { get; set; }
        public Nullable<System.Guid> Payroll_Period_ID { get; set; }
        public string Payroll_Period { get; set; }
        public string Batch_Number { get; set; }
        public string Source_Account_Bank { get; set; }
        public string Debit_Account_Number { get; set; }
        public string Debit_Account_Name { get; set; }
        public string Debit_Account_Address { get; set; }
        public string Employee_No { get; set; }
        public string Full_Name { get; set; }
        public string User_Reference_Number { get; set; }
        public string Employee_Bank_Account { get; set; }
        public string Employee_Bank_Code { get; set; }
        public string Employee_Account_Name { get; set; }
        public Nullable<decimal> Employee_Salary_Transferred { get; set; }
        public string Employee_Status_Transfer { get; set; }
        public string Transfer_Type_Detail { get; set; }
        public string Description { get; set; }
        public string Transfer_Message { get; set; }
        public Nullable<int> Total_Employee { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public string Currency_Code { get; set; }
        public string Payment_Set_Code { get; set; }
        public string Debit_Account_ID { get; set; }
        public Nullable<System.DateTime> Transfer_Date { get; set; }
        public string Batch_Payment_Status { get; set; }
        public Nullable<int> Authorize_Status { get; set; }
        public Nullable<int> Status_Code { get; set; }
    }
}
