//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Timeline_Mobile
    {
        public long Id_Row { get; set; }
        public Nullable<System.Guid> id_Timeline { get; set; }
        public System.Guid Organization_ID { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public string Menu { get; set; }
        public string Tittle { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public Nullable<System.Guid> Left_Icon { get; set; }
        public Nullable<System.Guid> Right_Icon { get; set; }
        public Nullable<System.Guid> Reference_ID { get; set; }
        public Nullable<System.DateTime> Created_DateTime { get; set; }
        public string Created_By { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<bool> Is_Read { get; set; }
        public string Menu_Icon { get; set; }
        public string Button_Icon { get; set; }
    }
}
