//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_User_Role_Menu
    {
        public long Id { get; set; }
        public System.Guid User_Role_Id { get; set; }
        public System.Guid User_ID { get; set; }
        public string Username { get; set; }
        public System.Guid Role_ID { get; set; }
        public string Role_Code { get; set; }
        public string Role_Description { get; set; }
        public System.Guid Organization_ID { get; set; }
        public string Organization_Code { get; set; }
        public string Organization_Name { get; set; }
        public string Menu_Name { get; set; }
    }
}
