//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MODEL.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_User_Report_Attendance
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> User_Id { get; set; }
        public Nullable<System.Guid> Employee_Id { get; set; }
        public string Employee_No { get; set; }
        public string Full_Name { get; set; }
        public Nullable<System.Guid> Organization_Id { get; set; }
        public string Organization_Code { get; set; }
        public string Organization_Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Day_Time_In { get; set; }
        public Nullable<System.DateTime> Day_Time_Out { get; set; }
        public string Description_Time_In { get; set; }
        public string Description_Time_Out { get; set; }
    }
}
